CREATE TABLE USER_TABLE (
    ID INTEGER UNIQUE AUTO_INCREMENT,
    NIM VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    GENDER VARCHAR(255) NOT NULL,
    HOBBY VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);